name: Lints

on:
  pull_request:
    branches: [ master ]

jobs:
  store-pr:
    name: Store PR number
    runs-on: ubuntu-latest
    steps:
    - name: Save PR number
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/NR
    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/

  formatting:
    name: Check formatting (invalid/format)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26'
        elixir-version: '1.16'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Fetch dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted

  credo:
    name: Check our credo (invalid/credo)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26'
        elixir-version: '1.16'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix do deps.get, deps.compile
    - name: Run Credo
      run: mix credo --all
